apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-demo-prod

helmGlobals:
  chartHome: ../../helm

helmCharts:
  - name: devops-demo-app
    releaseName: devops-demo-app
    namespace: devops-demo-prod
    valuesFile: values.yaml
    includeCRDs: false
