image:
  repository: localhost:5000/devops-demo-app
  tag: prod-2-792c5b9
  pullPolicy: IfNotPresent

replicaCount: 3

config:
  enabled: true
  data:
    NODE_ENV: production
    PORT: "8080"
    APP_ENV: prod

deployment:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 2
