apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-demo-staging

helmGlobals:
  chartHome: ../../helm

helmCharts:
  - name: devops-demo-app
    releaseName: devops-demo-app-staging
    namespace: devops-demo-staging
    valuesFile: values.yaml
    includeCRDs: false
