apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-demo-dev

helmGlobals:
  chartHome: ../../helm

helmCharts:
  - name: devops-demo-app
    releaseName: devops-demo-app-dev
    namespace: devops-demo-dev
    valuesFile: values.yaml
    includeCRDs: false
