apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MADARAKZ/devops-test.git
    targetRevision: main
    path: gitops/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-demo-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  revisionHistoryLimit: 10
