apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MADARAKZ/devops-test.git
    targetRevision: staging
    path: gitops/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-demo-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
