apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MADARAKZ/devops-test.git
    targetRevision: main
    path: gitops/dev
    kustomize:
      buildOptions: --enable-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
